### ISSUE TITLE
Fix hydra

### ISSUE THREAD

**Issue by vic-bart** [MonashNovaRover/nova#683]
### **Context**
[Hydra](https://github.com/NixOS/hydra) 🐉 is a Nix-based continuous build system that hosts nix-build/shell results on a server, allowing users to pull required nix-store filepaths from the server during nix-build/shell instead of creating them locally. 
TL;DR it cuts down build time by spending less time compiling, and more time downloading. 

But it's not functioning as expected. The status is unclear, but without hydra, the software ci/cd is significantly comprimised. Even worse, the members that understand hydra are not available to work on this.

### **TODO**
- Figure out what's going on with hydra
- Get it working

Tags for Notion Integration:
tag:autonomous;tag:software;tag:nixfiles;tag:ci/cd;tag:investigation

**Comment by Redecorating** [comment]
This issue right?

```bash
$ nix-instantiate ~/nova/nixfiles/ci/jobsets/workspaces.nix  --arg nixpkgs '<nixpkgs>' --arg nova-monorepo ~/nova  --arg supportedSystems '[ "x86_64-linux" ]' --argstr rosDistro jazzy -A x86_64-linux
error:
       … while evaluating the attribute 'hydraPatchedWorkspace'
         at /home/nova/nova/nixfiles/ci/workspaces.nix:5:3:
            4|   workspace = (if rosDistro == null then novaPkgs.ros else novaPkgs.rosPackages.${rosDistro}).nova-workspace;
            5|   hydraPatchedWorkspace = workspace.override
             |   ^
            6|     # Some x86_64 packages fail to build in QEMU on Aarch64. Workarounds

       … while evaluating the attribute 'pkgs'
         at /home/nova/nova/nixfiles/default.nix:141:5:
          140|
          141|     pkgs = novaPkgs;
             |     ^
          142|

       (stack trace truncated; use '--show-trace' to show the full, detailed trace)

       error: attribute 'hostPlatform' missing
       at /home/nova/nova/nixfiles/default.nix:66:19:
           65|     localSystem = pkgs.buildPlatform.system;
           66|     crossSystem = pkgs.hostPlatform.system;
             |                   ^
           67|     config = pkgs.config // {
       Did you mean rustPlatform?
```

**Comment by Redecorating** [comment]
maybe fixed by ee3895c17a1757ca82917865edf9e9b09e0e8095

**Comment by FelicityMatt** [comment]
@Redecorating Looks like the error is still appearing: https://hydra.novarover.space/eval/552949#tabs-errors

**Comment by Redecorating** [comment]
> @Redecorating Looks like the error is still appearing: https://hydra.novarover.space/eval/552949#tabs-errors

that build is before the fix was put on master.

**Comment by Redecorating** [comment]
I think ppl need to rebase ontop of master and then hydra will build prs. Some packages need hydra vomit still

**Comment by FelicityMatt** [comment]
yeah looks like the most recent build was successfu?!l: https://hydra.novarover.space/eval/590072?name=workspaces

Sorry this is my first time looking at hydra 😵

**Comment by vic-bart** [comment]
Hydra is evaluating new jobsets, yipee!
